spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: biguser
    password: bigpass123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
  main:
    allow-bean-definition-overriding: true